### PR TITLE
Fixed various errors for some Rebel Alliance ships

### PR DESCRIPTION
**Pull request by acosoi**

### CODE REVIEW

**Comment by FreakyDug** [comment]
Are the two Norra pilot abilities definitely different on the final cards that shipped?

**Comment by acosoi** [comment]
For BTL-A4 Y-wing, the screenshot [here ](https://www.fantasyflightgames.com/en/news/2018/6/18/begin-attack-run/) doesn't use "you may", it just says "add 1 [Evade]".

Unfortunately, I couldn't find an official screenshot of the ARC-170 pilot card for Norra. The old one uses "you may", though it would make more sense for the two abilities to be identical.

Would it make more sense to revert the change to ARC-170 and assume that the two abilities will be consistent across both versions of the pilot?

**Comment by FreakyDug** [comment]
Since it's not a difference that makes a meaningful difference in play, I can't imagine it's intentional, but I wouldn't put it past FFG to have printed them differently in the same box. 

@guidokessels Do you prefer to go with the more logical option we can infer or stick to what's on the cards (as far as we can tell)?

**Comment by guidokessels** [comment]
Lets stick to what's on the cards. If FFG rules they should be the same we can change it again.

**Comment by guidokessels** [comment]
Thanks for the changes!

**Pull request merged**
