### PR TITLE
Proposal: XWS ids

### PR DESCRIPTION
**Pull request by guidokessels**
Added a proposal for XWS ids. 

Ids are generated as follows:
1. Take the English-language name as printed on the card
2. Lowercase the name
3. Convert non-ASCII characters to closest ASCII equivalent (to remove umlauts, etc.)
4. Remove non-alphanumeric characters
5. Check for collisions; If there’s a collision add a numeric identifier. (`sabinewren` -> `sabinewren-2`)
6. Check for collisions; If there’s a collision increase the numeric identifier until there is no collision. (`sabinewren-2` -> `sabinewren-3`)

Initial ordering has been done as follows:
1. Order alphabetically by ship name
2. Order by initiative
3. Order alphabetically by pilot name

### CODE REVIEW

**Comment by guidokessels** [comment]
@sirjorj, @mu0n: As we discussed on Slack. Let me know what you think

**Comment by Mu0n** [comment]
Looks good *everything breaks on September 13th*

**Comment by Mu0n** [comment]
Since there are already collisions to deal with (I think?), then populate this list by order of 2.0 SKU?

**Comment by sirjorj** [comment]
The SKUs for the conversion kits have a lot of pilots that get added at once.  I'm not sure that idea will hold up.

Here's a more heavy handed idea:
* Factions can be reduced to a 2 character code (RB, IM, SC, FO, RS).
* The dials have a 2 or 3 character ship code
* Pilot name gets the same treatment as xws

Ex: IMTFhowlrunner or IM_TF_howlrunner - something like that.

This would NOT handle the 1.0 Poe Dameron scenario, but I highly doubt that will translate to 2.0.  Just in case, maybe it wouldn't hurt to include initiative in the scheme anyway (IM_TF_5_Hownrunner).  That could make the default ordering pretty convenient.

Does that seem reasonable or is it overkill?

**Comment by Mu0n** [comment]
Eli's thoughts on a UNIQUE PILOT KEY:

add a new key:value inside each pilot
where key="xws2"
value="faction-ship-pilot-sku" (but where -sku is optional and only needed in case there's a collision)
e.g. galacticempire-tielnfighter-howlrunner
and applying the same logic to 1st edition's Poe Dameron ps9, we'd have gotten
resistance-t70xwing-poedameron-swx57

My own additional thoughts:
missing JSON properties
per pilot:
List<String> actions
List<String> conditions

suggested faction names:
rebelalliance
galacticempire
scumandvillainy
firstorder
resistance
galacticrepublic
separatistarmy

**Comment by Mu0n** [comment]
another key:value to add to every pilot:
"shipability":"description"
see: http://xhud.sirjorj.com/xwing.cgi/pilot2?pilot=autopilotdrone&faction=scum&ship=escapecraft
vs
http://xhud.sirjorj.com/xwing.cgi/pilot2?pilot=outerrimpioneer&faction=scum&ship=escapecraft

as an example where 2 pilots of a single ship type can have different ship abilities

**Comment by guidokessels** [comment]
This was replaced by https://github.com/guidokessels/xwing-data2/pull/20 after discussions on Slack.

**Pull request closed without merging**
