### PR TITLE
added Japanese localization of pilot abilities

### PR DESCRIPTION
**Pull request by urbknu**
The Japanese abilities are fetched from https://wikiwiki.jp/x-wing2/

Created for possible usage in TTS and YASB, but thought this to be relevant for the xwing-data2 project

### CODE REVIEW

**Comment by urbknu** [comment]
TODO: add ship abilities

**Comment by danrs** [comment]
I don't speak Japanese, so about the only thing I can do is check for valid json and approve. Given how long this has sat here, I suspect that there aren't any other interested Japanese speakers who want to review it. Furthermore, incorrect Japanese text is probably better than no Japanese text, so I'm inclined to merge this.

**Comment by danrs** [comment]
No comments from other contributors, so I'm merging

**Comment by guidokessels** [comment]
I [moved](https://github.com/guidokessels/xwing-data2/pull/452) this from `data/pilots/localization.pilots.json` to `data/localization.pilots.json` so it is next to the other translations.

We should probably look into merging this with the `translation.json` file.

**Pull request merged**
