### PR TITLE
Add hotshots and aces and a few recent ships pilots

### PR DESCRIPTION
**Pull request by Gan0n29**

### CODE REVIEW

**Comment by FreakyDug** [comment]
Thanks!

**Comment by Gan0n29** [comment]
Hi, I started a translation file too : https://github.com/Gan0n29/xwing-data2/blob/master/data/translation.json   De : Philip DouglasEnvoyé le :dimanche 31 mai 2020 17:42À : guidokessels/xwing-data2Cc : Gan0n29; AuthorObjet :Re: [guidokessels/xwing-data2] Add hotshots and aces and a few recent ships pilots (#349) Thanks!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sirjorj** [comment]
Your BTL-B Y-wing entries are including the Ion Cannon [CANNON] instead of the Ion Cannon Turret {TURRET].

Your work here inspired me to update my data  and compare it with yours to keep them in sync.  Thanks for doing this! :)

**Comment by sirjorj** [comment]
I think you also have a wrong upgrade on the Zizi Tlo quickbuild

**Comment by Gan0n29** [comment]
Hi,
Thanks, I just updated those ships and made a pull request.

**Pull request merged**
