### PR TITLE
Fixing xws for upsilon and tie interceptor

### PR DESCRIPTION
**Pull request by zacharyp**

### CODE REVIEW

**Comment by FreakyDug** [comment]
@guidokessels is worried these xws names have been this way too long and we'll break compatibility: https://github.com/guidokessels/xwing-data2/pull/213#pullrequestreview-193486989

**Comment by zacharyp** [comment]
That's what I've been saying for months as well. I figure we are about to go through a bunch of changes due to Wave 3, so this might be a good time to fix?

**Comment by FreakyDug** [comment]
We'll need to coordinate the change with other XWS producers and consumers.

**Comment by zacharyp** [comment]
Thing is, most consumers are already handling this problem, because yasb exports these corrected xws values already.

**Comment by FreakyDug** [comment]
Oh, I thought they were also using the wrong ones. Does anyone else?

**Comment by zacharyp** [comment]
Not sure, take a poll in 'tech' chat? 👍

**Comment by FreakyDug** [comment]
Yeah, that sounds like a good idea.

**Pull request closed without merging**
