### PR TITLE
Add cards from RZ-2 A-wing preview

### PR DESCRIPTION
**Pull request by FreakyDug**

### CODE REVIEW

**Comment by kelvinleague** [comment]
I'm getting an extraneous `}` parsing error in this branch

**Comment by FreakyDug** [comment]
@kelvinleague does the error you're getting point to where? It's parsing ok in R2-D7 and VS Code's JSON error checker isn't finding anything.

**Comment by kelvinleague** [comment]
It looks like there's a hanging comma at the end of line 61 of the Rz-2 file. I think generally it's safe for a parser but my node instance complains about it and aborts when parsing it.

**Comment by FreakyDug** [comment]
The comma on line 61 is necessary, but I fixed an extraneous comma on line 60 in 6ea1691.

**Comment by kelvinleague** [comment]
Oops! That's the one I meant. The one after the image link.

**Comment by FreakyDug** [comment]
If you pull the latest commit in this branch, it should be fixed.

**Comment by kelvinleague** [comment]
Any idea what happened to GuidoKessel? There's bunch of PRs that are getting stale.

**Comment by FreakyDug** [comment]
I heard he's been busy organising Nordic Nationals. This branch on my fork has all the new stuff merged in for now: https://github.com/FreakyDug/xwing-data2/tree/bot

**Comment by guidokessels** [comment]
Thanks!

**Pull request merged**
